# Generated by Django 3.2.4 on 2021-07-02 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Title')),
                ('image', models.CharField(max_length=127, verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Case_study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Title')),
                ('image', models.ImageField(upload_to='recipe_images', verbose_name='Image')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_studies', to='pages.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Case_study',
                'verbose_name_plural': 'Case_studies',
            },
        ),
    ]
