# Generated by Django 3.2.4 on 2021-07-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_case_study_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attorneys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Name')),
                ('title', models.CharField(max_length=127, verbose_name='Title')),
                ('image', models.ImageField(max_length=127, upload_to='attorneys', verbose_name='Image')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attorney',
                'verbose_name_plural': 'Attorneys',
            },
        ),
        migrations.CreateModel(
            name='Practice_areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Title')),
                ('image', models.CharField(max_length=127, verbose_name='Image')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Practice_area',
                'verbose_name_plural': 'Practice_areas',
            },
        ),
        migrations.AlterField(
            model_name='case_study',
            name='image',
            field=models.ImageField(upload_to='case_study_images', verbose_name='Image'),
        ),
    ]
