# Generated by Django 3.2.4 on 2021-07-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210702_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='practice_areas',
            name='image',
            field=models.ImageField(max_length=127, upload_to='practice_area_images', verbose_name='Image'),
        ),
    ]
